---
deployment:
  tasks:
    - export DEPLOYPATH=/home/repositories/nextJS-redux-implementation/
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install --production
    